local t = fkst.test
local core = require("core")
local site = require("site")
local en = require("locales.en")
local zh = require("locales.zh")

local function expected_page(locale, catalog, nav_href, permalink, other_href)
  local language_current = locale == "en" and en["language.label"] or zh["language.label"]
  local language_other = locale == "en" and zh["language.label"] or en["language.label"]
  local lang = locale == "en" and "en" or "zh-Hans"
  local lines = {
    "---",
    "generated: true",
    "generator: FKST",
    "translationKey: about",
    "layout: layouts/page.njk",
    "permalink: " .. permalink,
    "lang: " .. lang,
    "title: " .. catalog["about.title"],
    "description: " .. catalog["about.description"],
    "brandHref: /",
    "nav:",
    "  - label: " .. catalog["nav.home"],
    "    href: " .. nav_href,
    "  - label: " .. catalog["nav.architecture"],
    "    href: " .. (locale == "en" and "/architecture.html" or "/zh/architecture.html"),
    "  - label: " .. catalog["nav.doctrine"],
    "    href: " .. (locale == "en" and "/doctrine.html" or "/zh/doctrine.html"),
    "languageSwitch:",
  }
  if locale == "en" then
    table.insert(lines, "  - label: " .. language_current)
    table.insert(lines, "    current: true")
    table.insert(lines, "  - label: " .. language_other)
    table.insert(lines, "    href: " .. other_href)
  else
    table.insert(lines, "  - label: " .. language_other)
    table.insert(lines, "    href: " .. other_href)
    table.insert(lines, "  - label: " .. language_current)
    table.insert(lines, "    current: true")
  end
  table.insert(lines, "footerText: " .. catalog["about.footer"])
  table.insert(lines, "---")
  table.insert(lines, "<!-- @generated by FKST. Do not edit. -->")
  table.insert(lines, catalog["about.body.heading"])
  table.insert(lines, catalog["about.body.blank1"])
  table.insert(lines, catalog["about.body.intro"])
  table.insert(lines, catalog["about.body.blank2"])
  table.insert(lines, catalog["about.body.boundary"])
  table.insert(lines, catalog["about.body.blank3"])
  table.insert(lines, catalog["about.body.proof"])
  table.insert(lines, "")
  return table.concat(lines, "\n")
end

local EXPECTED_EN = expected_page("en", en, "/", "/about/", "/zh/about/")
local EXPECTED_ZH = expected_page("zh", zh, "/zh/", "/zh/about/", "/about/")
local EXPECTED_ROUTES = '{"routes":{"about":{"en":{"lang":"en","output_path":"_generated/about/index.md","permalink":"/about/","translationKey":"about"},"zh":{"lang":"zh","output_path":"_generated/zh/about/index.md","permalink":"/zh/about/","translationKey":"about"}}},"schema_version":"fkst.site.routes.v1"}'

local function digest_for(content)
  if content == EXPECTED_EN then
    return "1111111111111111111111111111111111111111111111111111111111111111"
  end
  if content == EXPECTED_ZH then
    return "2222222222222222222222222222222222222222222222222222222222222222"
  end
  if content == EXPECTED_ROUTES .. "\n" then
    return "3333333333333333333333333333333333333333333333333333333333333333"
  end
  error("unexpected content passed to digest provider: " .. tostring(content))
end

local function file_by_path(artifact_set, path)
  for _, item in ipairs(artifact_set.files) do
    if item.path == path then
      return item.content
    end
  end
  error("missing generated path: " .. path)
end

local function nonce()
  return tostring({}):gsub("[^%w._-]", "_")
end

local function runtime_root(name)
  return "/tmp/fkst-website-test/site-gen/" .. tostring(now()) .. "/" .. nonce() .. "/" .. name
end

local function opts(name)
  return {
    env = {
      FKST_RUNTIME_ROOT = runtime_root(name),
    },
  }
end

local function run_generate(run_opts)
  return t.run_department("departments/generate/main.lua", {
    queue = "site-gen.site_gen_generate",
    payload = {},
  }, run_opts)
end

return {
  test_persistence_class_is_stateless_adapter = function()
    t.eq(core.persistence_class(), "stateless_adapter")
  end,

  test_renders_bilingual_about_pages_with_stable_front_matter = function()
    t.eq(core.render_page_markdown(site.pages[1], "en"), EXPECTED_EN)
    t.eq(core.render_page_markdown(site.pages[1], "zh"), EXPECTED_ZH)
  end,

  test_build_artifact_set_is_canonical_and_manifested = function()
    local artifacts = core.build_artifact_set(site, digest_for)
    t.eq(file_by_path(artifacts, "site/src/_generated/about/index.md"), EXPECTED_EN)
    t.eq(file_by_path(artifacts, "site/src/_generated/zh/about/index.md"), EXPECTED_ZH)
    t.eq(file_by_path(artifacts, "site/src/_data/fkst/routes.json"), EXPECTED_ROUTES .. "\n")
    t.eq(artifacts.routes_json, EXPECTED_ROUTES .. "\n")
    t.eq(
      artifacts.manifest_json,
      '{"documents":[{"path":"src/_data/fkst/routes.json","schema_version":"fkst.site.routes.v1","sha256":"3333333333333333333333333333333333333333333333333333333333333333"},{"path":"src/_generated/about/index.md","schema_version":"fkst.site.generated.page.v1","sha256":"1111111111111111111111111111111111111111111111111111111111111111"},{"path":"src/_generated/zh/about/index.md","schema_version":"fkst.site.generated.page.v1","sha256":"2222222222222222222222222222222222222222222222222222222222222222"}],"generator":"site-gen","schema_version":"fkst.site.generated.manifest.v1"}\n'
    )
    t.eq(artifacts.manifest_json:find("generated_at", 1, true), nil)
    t.eq(artifacts.manifest_json:find(tostring(now()), 1, true), nil)
  end,

  test_validation_fails_closed_on_unsafe_description = function()
    local bad = {
      pages = {
        {
          slug = "../bad",
          translations = site.pages[1].translations,
        },
      },
    }
    local ok = pcall(core.build_artifact_set, bad, digest_for)
    t.eq(ok, false)
  end,

  test_write_outputs_cmd_is_bounded_and_atomic = function()
    local artifacts = core.build_artifact_set(site, digest_for)
    local mkdir = core.mkdir_outputs_cmd(core.default_output_config(), artifacts)
    t.is_true(mkdir:find("mkdir -p", 1, true) ~= nil)
    t.is_true(mkdir:find("'site/src/_generated/about'", 1, true) ~= nil)
    t.is_true(mkdir:find("'site/src/_generated/zh/about'", 1, true) ~= nil)
    t.is_true(mkdir:find("'site/src/_data/fkst'", 1, true) ~= nil)

    local cmd = core.write_outputs_cmd(core.default_output_config(), artifacts)
    t.is_true(cmd:find("mkdir -p 'site/src/_generated/about'", 1, true) ~= nil)
    t.is_true(cmd:find("site/src/_generated/about/index.md.tmp", 1, true) ~= nil)
    t.is_true(cmd:find("mv 'site/src/_generated/about/index.md.tmp' 'site/src/_generated/about/index.md'", 1, true) ~= nil)
    t.is_true(cmd:find("site/src/_data/fkst/routes.json.tmp", 1, true) ~= nil)
    t.is_true(cmd:find("site/src/_data/fkst/manifest.json.tmp", 1, true) ~= nil)
    t.eq(
      core.move_output_cmd("site/src/_generated/about/index.md"),
      "mv 'site/src/_generated/about/index.md.tmp' 'site/src/_generated/about/index.md'"
    )

    artifacts.files[1].path = "site/src/index.njk"
    local ok = pcall(core.write_outputs_cmd, core.default_output_config(), artifacts)
    t.eq(ok, false)
  end,

  test_sha256_command_and_parse = function()
    t.eq(core.sha256_hex("abc"), "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
    t.eq(core.sha256_hex(""), "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")
    local cmd = core.sha256_hex_cmd("abc")
    t.is_true(cmd:find("sha256sum", 1, true) ~= nil)
    t.is_true(cmd:find("shasum -a 256", 1, true) ~= nil)
    local digest, err = core.parse_sha256_hex_output("BA7816BF8F01CFEA414140DE5DAE2223B00361A396177A9CB410FF61F20015AD  -\n")
    t.eq(err, nil)
    t.eq(digest, "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
  end,

  test_department_writes_generated_site_sources = function()
    t.mock_command("mkdir -p", { stdout = "", exit_code = 0 })
    t.mock_command("mv 'site/src/_data/fkst/routes.json.tmp'", { stdout = "", exit_code = 0 })
    t.mock_command("mv 'site/src/_generated/about/index.md.tmp'", { stdout = "", exit_code = 0 })
    t.mock_command("mv 'site/src/_generated/zh/about/index.md.tmp'", { stdout = "", exit_code = 0 })
    t.mock_command("mv 'site/src/_data/fkst/manifest.json.tmp'", { stdout = "", exit_code = 0 })

    local result = run_generate(opts("department"))
    t.eq(result.exit_code, 0)
    local calls = t.command_calls()
    t.eq(#calls, 5)
    t.is_true(calls[1].rendered:find("site/src/_data/fkst", 1, true) ~= nil)
    t.is_true(calls[2].rendered:find("site/src/_data/fkst/routes.json", 1, true) ~= nil)
    t.is_true(calls[3].rendered:find("site/src/_generated/about/index.md", 1, true) ~= nil)
    t.is_true(calls[4].rendered:find("site/src/_generated/zh/about/index.md", 1, true) ~= nil)
    t.is_true(calls[5].rendered:find("site/src/_data/fkst/manifest.json", 1, true) ~= nil)
  end,

  test_fire_raiser_generate_routes_to_generator = function()
    t.mock_command("mkdir -p", { stdout = "", exit_code = 0 })
    t.mock_command("mv 'site/src/_data/fkst/routes.json.tmp'", { stdout = "", exit_code = 0 })
    t.mock_command("mv 'site/src/_generated/about/index.md.tmp'", { stdout = "", exit_code = 0 })
    t.mock_command("mv 'site/src/_generated/zh/about/index.md.tmp'", { stdout = "", exit_code = 0 })
    t.mock_command("mv 'site/src/_data/fkst/manifest.json.tmp'", { stdout = "", exit_code = 0 })

    local trace = t.fire_raiser("generate")
    t.eq(trace.source_ref.kind, "cron")
    t.eq(trace.source_payload.raiser, "site-gen.generate")
    t.eq(trace.routed_to[1], "site-gen.generate")
    if trace.consumer_result.status ~= "accepted" then
      error(trace.consumer_result.message or "fire_raiser consumer failed")
    end
    t.eq(trace.consumer_result.status, "accepted")
    t.eq(#trace.raised, 0)
  end,
}
