local M = {}

M.PAGE_SCHEMA_VERSION = "fkst.site.generated.page.v1"
M.ROUTES_SCHEMA_VERSION = "fkst.site.routes.v1"
M.MANIFEST_SCHEMA_VERSION = "fkst.site.generated.manifest.v1"
M.GENERATED_BANNER = "@generated by FKST. Do not edit."
M.DEFAULT_GENERATED_ROOT = "site/src/_generated"
M.DEFAULT_DATA_ROOT = "site/src/_data/fkst"
M.ROUTES_FILENAME = "routes.json"
M.MANIFEST_FILENAME = "manifest.json"

local UINT32_MASK = 0xffffffff
local SHA256_K = {
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5,
  0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
  0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
  0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
  0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
  0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
  0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
  0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
  0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
}

local LOCALE_CONFIG = {
  en = {
    output_prefix = "",
    permalink_prefix = "",
    brandHref = "/",
  },
  zh = {
    output_prefix = "zh",
    permalink_prefix = "/zh",
    brandHref = "/",
  },
}

local LOCALE_ORDER = { "en", "zh" }

function M.persistence_class()
  return "stateless_adapter"
end

local function is_array(value)
  if type(value) ~= "table" then
    return false
  end
  local count = 0
  for key, _ in pairs(value) do
    if type(key) ~= "number" or key < 1 or math.floor(key) ~= key then
      return false
    end
    count = count + 1
  end
  return count == #value
end

local function json_string(value)
  if type(value) ~= "string" then
    error("json_string requires a string")
  end
  return '"'
    .. value:gsub('[%z\001-\031\\"]', function(char)
      if char == '"' then
        return '\\"'
      end
      if char == "\\" then
        return "\\\\"
      end
      local byte = string.byte(char)
      if byte == 8 then
        return "\\b"
      end
      if byte == 9 then
        return "\\t"
      end
      if byte == 10 then
        return "\\n"
      end
      if byte == 12 then
        return "\\f"
      end
      if byte == 13 then
        return "\\r"
      end
      return string.format("\\u%04x", byte)
    end)
    .. '"'
end

local function json_number(value)
  if type(value) ~= "number" then
    error("json_number requires a number")
  end
  if value ~= value or value == math.huge or value == -math.huge then
    error("json_number requires a finite number")
  end
  if math.floor(value) == value then
    return string.format("%.0f", value)
  end
  return tostring(value)
end

local encode_json_value

local function sorted_string_keys(value)
  local keys = {}
  for key, item in pairs(value) do
    if type(key) == "string" and item ~= nil then
      table.insert(keys, key)
    end
  end
  table.sort(keys)
  return keys
end

local function encode_json_object(value)
  local parts = {}
  for _, key in ipairs(sorted_string_keys(value)) do
    table.insert(parts, json_string(key) .. ":" .. encode_json_value(value[key]))
  end
  return "{" .. table.concat(parts, ",") .. "}"
end

local function encode_json_array(value)
  local parts = {}
  for index = 1, #value do
    table.insert(parts, encode_json_value(value[index]))
  end
  return "[" .. table.concat(parts, ",") .. "]"
end

function encode_json_value(value)
  local kind = type(value)
  if kind == "string" then
    return json_string(value)
  end
  if kind == "number" then
    return json_number(value)
  end
  if kind == "boolean" then
    if value then
      return "true"
    end
    return "false"
  end
  if kind == "nil" then
    return "null"
  end
  if kind == "table" then
    if is_array(value) then
      return encode_json_array(value)
    end
    return encode_json_object(value)
  end
  error("unsupported JSON value type: " .. kind)
end

function M.encode_json(value)
  return encode_json_value(value)
end

local function add32(...)
  local sum = 0
  for index = 1, select("#", ...) do
    sum = (sum + select(index, ...)) & UINT32_MASK
  end
  return sum
end

local function rrotate(value, bits)
  return ((value >> bits) | ((value << (32 - bits)) & UINT32_MASK)) & UINT32_MASK
end

local function word_from_bytes(message, offset)
  local b1, b2, b3, b4 = message:byte(offset, offset + 3)
  return (((b1 or 0) << 24) | ((b2 or 0) << 16) | ((b3 or 0) << 8) | (b4 or 0)) & UINT32_MASK
end

local function uint32_hex(value)
  return string.format("%08x", value & UINT32_MASK)
end

function M.sha256_hex(message)
  if type(message) ~= "string" then
    error("sha256 input must be a string")
  end

  local bit_len = #message * 8
  local high = math.floor(bit_len / 0x100000000)
  local low = bit_len % 0x100000000
  local padding = { string.char(0x80) }
  while ((#message + #padding) % 64) ~= 56 do
    table.insert(padding, string.char(0))
  end
  table.insert(padding, string.char(
    math.floor(high / 0x1000000) % 256,
    math.floor(high / 0x10000) % 256,
    math.floor(high / 0x100) % 256,
    high % 256,
    math.floor(low / 0x1000000) % 256,
    math.floor(low / 0x10000) % 256,
    math.floor(low / 0x100) % 256,
    low % 256
  ))

  local bytes = message .. table.concat(padding)
  local h1, h2, h3, h4 = 0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a
  local h5, h6, h7, h8 = 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19

  for chunk = 1, #bytes, 64 do
    local w = {}
    for i = 0, 15 do
      w[i] = word_from_bytes(bytes, chunk + i * 4)
    end
    for i = 16, 63 do
      local s0 = rrotate(w[i - 15], 7) ~ rrotate(w[i - 15], 18) ~ (w[i - 15] >> 3)
      local s1 = rrotate(w[i - 2], 17) ~ rrotate(w[i - 2], 19) ~ (w[i - 2] >> 10)
      w[i] = add32(w[i - 16], s0, w[i - 7], s1)
    end

    local a, b, c, d = h1, h2, h3, h4
    local e, f, g, h = h5, h6, h7, h8
    for i = 0, 63 do
      local s1 = rrotate(e, 6) ~ rrotate(e, 11) ~ rrotate(e, 25)
      local ch = (e & f) ~ ((~e) & g)
      local temp1 = add32(h, s1, ch, SHA256_K[i + 1], w[i])
      local s0 = rrotate(a, 2) ~ rrotate(a, 13) ~ rrotate(a, 22)
      local maj = (a & b) ~ (a & c) ~ (b & c)
      local temp2 = add32(s0, maj)
      h = g
      g = f
      f = e
      e = add32(d, temp1)
      d = c
      c = b
      b = a
      a = add32(temp1, temp2)
    end

    h1, h2, h3, h4 = add32(h1, a), add32(h2, b), add32(h3, c), add32(h4, d)
    h5, h6, h7, h8 = add32(h5, e), add32(h6, f), add32(h7, g), add32(h8, h)
  end

  return table.concat({
    uint32_hex(h1),
    uint32_hex(h2),
    uint32_hex(h3),
    uint32_hex(h4),
    uint32_hex(h5),
    uint32_hex(h6),
    uint32_hex(h7),
    uint32_hex(h8),
  })
end

local function require_string(value, context)
  if type(value) ~= "string" or value == "" then
    error(context .. " must be a non-empty string")
  end
  return value
end

local function require_array(value, context)
  if not is_array(value) then
    error(context .. " must be an array")
  end
  return value
end

local function validate_catalog_key(key, context)
  require_string(key, context)
  if key:match("^[A-Za-z0-9_.-]+$") == nil then
    error(context .. " must be a locale catalog key")
  end
  return key
end

local function locale_catalog(locale)
  if LOCALE_CONFIG[locale] == nil then
    error("unsupported locale: " .. tostring(locale))
  end
  local catalog = require("locales." .. locale)
  if type(catalog) ~= "table" then
    error("locale catalog must return an object")
  end
  return catalog
end

local function catalog_value(catalog, key, context)
  local value = catalog[validate_catalog_key(key, context)]
  if type(value) ~= "string" then
    error(context .. " is missing from locale catalog")
  end
  return value
end

local function translated_value(translation, catalog, field, key_field, context)
  if type(translation[field]) == "string" then
    return translation[field]
  end
  return catalog_value(catalog, translation[key_field], context)
end

local function validate_slug(slug)
  require_string(slug, "page slug")
  if slug:match("^[a-z0-9][a-z0-9-]*$") == nil then
    error("page slug must use lowercase letters, digits, and hyphens")
  end
  return slug
end

local function validate_path_part(part, context)
  require_string(part, context)
  if part == "." or part == ".." or part:find("/", 1, true) or part:find("\\", 1, true) then
    error(context .. " is not a safe path segment")
  end
  if part:find("%z") or part:find("\n", 1, true) or part:find("\r", 1, true) then
    error(context .. " contains an invalid path character")
  end
  return part
end

local function validate_output_root(path, expected)
  require_string(path, "output root")
  if path ~= expected then
    error("output root must be " .. expected)
  end
  return path
end

local function path_join(...)
  local parts = { ... }
  local out = {}
  for _, part in ipairs(parts) do
    if part ~= "" then
      table.insert(out, part)
    end
  end
  return table.concat(out, "/")
end

local function page_output_path(generated_root, locale, slug)
  local cfg = LOCALE_CONFIG[locale]
  if cfg == nil then
    error("unsupported locale: " .. tostring(locale))
  end
  if cfg.output_prefix == "" then
    return path_join(generated_root, slug, "index.md")
  end
  return path_join(generated_root, cfg.output_prefix, slug, "index.md")
end

local function page_permalink(locale, slug)
  local cfg = LOCALE_CONFIG[locale]
  if cfg == nil then
    error("unsupported locale: " .. tostring(locale))
  end
  if cfg.permalink_prefix == "" then
    return "/" .. slug .. "/"
  end
  return cfg.permalink_prefix .. "/" .. slug .. "/"
end

local function frontmatter_scalar(key, value)
  return key .. ": " .. tostring(value)
end

local function frontmatter_array(key, items)
  local lines = { key .. ":" }
  for _, item in ipairs(items) do
    if type(item) ~= "table" then
      error(key .. " entries must be objects")
    end
    local label = require_string(item.label, key .. " label")
    table.insert(lines, "  - label: " .. label)
    if item.href ~= nil then
      table.insert(lines, "    href: " .. require_string(item.href, key .. " href"))
    elseif item.current ~= true then
      error(key .. " href must be a non-empty string")
    end
    if item.current ~= nil then
      table.insert(lines, "    current: " .. tostring(item.current))
    end
    if item.external ~= nil then
      table.insert(lines, "    external: " .. tostring(item.external))
    end
  end
  return lines
end

local function language_switch(locale, slug)
  local en_label = catalog_value(locale_catalog("en"), "language.label", "language label")
  local zh_label = catalog_value(locale_catalog("zh"), "language.label", "language label")
  if locale == "en" then
    return {
      { label = en_label, current = true },
      { label = zh_label, href = page_permalink("zh", slug) },
    }
  end
  return {
    { label = en_label, href = page_permalink("en", slug) },
    { label = zh_label, current = true },
  }
end

local function nav_items(translation, catalog)
  local raw = require_array(translation.nav or {}, "translation nav")
  local out = {}
  for _, item in ipairs(raw) do
    if type(item) ~= "table" then
      error("translation nav entries must be objects")
    end
    local label = item.label
    if label == nil then
      label = catalog_value(catalog, item.label_key, "translation nav label_key")
    end
    local entry = {
      label = require_string(label, "translation nav label"),
      href = require_string(item.href, "translation nav href"),
    }
    if item.current ~= nil then
      entry.current = item.current
    end
    if item.external ~= nil then
      entry.external = item.external
    end
    table.insert(out, entry)
  end
  return out
end

local function body_lines(translation, catalog)
  if translation.body ~= nil then
    local body = require_array(translation.body, "translation body")
    for _, line in ipairs(body) do
      if type(line) ~= "string" then
        error("translation body entries must be strings")
      end
    end
    return body
  end
  local keys = require_array(translation.body_keys, "translation body_keys")
  local body = {}
  for _, key in ipairs(keys) do
    table.insert(body, catalog_value(catalog, key, "translation body key"))
  end
  return body
end

function M.render_page_markdown(page, locale)
  if type(page) ~= "table" then
    error("page must be an object")
  end
  local slug = validate_slug(page.slug)
  local translation = page.translations and page.translations[locale]
  if type(translation) ~= "table" then
    error("missing translation for " .. tostring(locale))
  end
  local catalog = locale_catalog(locale)
  local body = body_lines(translation, catalog)
  local nav = nav_items(translation, catalog)
  local lang = require_string(translation.lang, "translation lang")
  local title = translated_value(translation, catalog, "title", "title_key", "translation title")
  local description = translated_value(translation, catalog, "description", "description_key", "translation description")
  local footer_text = translated_value(translation, catalog, "footerText", "footer_key", "translation footerText")
  local layout = require_string(page.layout or "layouts/page.njk", "page layout")

  local lines = {
    "---",
    frontmatter_scalar("generated", true),
    frontmatter_scalar("generator", "FKST"),
    frontmatter_scalar("translationKey", slug),
    frontmatter_scalar("layout", layout),
    frontmatter_scalar("permalink", page_permalink(locale, slug)),
    frontmatter_scalar("lang", lang),
    frontmatter_scalar("title", title),
    frontmatter_scalar("description", description),
    frontmatter_scalar("brandHref", LOCALE_CONFIG[locale].brandHref),
  }
  for _, line in ipairs(frontmatter_array("nav", nav)) do
    table.insert(lines, line)
  end
  for _, line in ipairs(frontmatter_array("languageSwitch", language_switch(locale, slug))) do
    table.insert(lines, line)
  end
  table.insert(lines, frontmatter_scalar("footerText", footer_text))
  table.insert(lines, "---")
  table.insert(lines, "<!-- " .. M.GENERATED_BANNER .. " -->")
  for _, line in ipairs(body) do
    table.insert(lines, line)
  end
  return table.concat(lines, "\n") .. "\n"
end

function M.sha256_hex_cmd(message)
  if type(message) ~= "string" then
    error("sha256 input must be a string")
  end
  local quoted = M.shell_single_quote(message)
  return "if command -v sha256sum >/dev/null 2>&1; then printf %s "
    .. quoted
    .. " | sha256sum | awk '{print $1}'; elif command -v shasum >/dev/null 2>&1; then printf %s "
    .. quoted
    .. " | shasum -a 256 | awk '{print $1}'; else echo 'sha256 command not found' >&2; exit 127; fi"
end

function M.parse_sha256_hex_output(stdout)
  if type(stdout) ~= "string" then
    return nil, "sha256 command stdout is not a string"
  end
  local digest = stdout:match("^%s*([0-9a-fA-F]+)")
  if digest == nil or #digest ~= 64 or digest:match("^[0-9a-fA-F]+$") == nil then
    return nil, "sha256 command did not return 64 hex characters"
  end
  return digest:lower(), nil
end

function M.shell_single_quote(value)
  return "'" .. tostring(value):gsub("'", "'\\''") .. "'"
end

local function sha256_hex(message, provider)
  if provider ~= nil then
    return provider(message)
  end
  return M.sha256_hex(message)
end

local function route_entry(slug, locale)
  return {
    lang = locale,
    output_path = (locale == "en" and ("_generated/" .. slug .. "/index.md"))
      or ("_generated/zh/" .. slug .. "/index.md"),
    permalink = page_permalink(locale, slug),
    translationKey = slug,
  }
end

local function site_source_path(path)
  local prefix = "site/"
  if path:sub(1, #prefix) ~= prefix then
    error("generated artifact path must be under site/")
  end
  return path:sub(#prefix + 1)
end

local function build_routes(pages)
  local routes = {}
  for _, page in ipairs(pages) do
    local slug = validate_slug(page.slug)
    routes[slug] = {
      en = route_entry(slug, "en"),
      zh = route_entry(slug, "zh"),
    }
  end
  return {
    routes = routes,
    schema_version = M.ROUTES_SCHEMA_VERSION,
  }
end

function M.build_artifact_set(site, sha256_provider)
  if type(site) ~= "table" then
    error("site description must be an object")
  end
  local pages = require_array(site.pages, "site pages")
  local files = {}
  local manifest_documents = {}

  for _, page in ipairs(pages) do
    local slug = validate_slug(page.slug)
    for _, locale in ipairs(LOCALE_ORDER) do
      local content = M.render_page_markdown(page, locale)
      local path = page_output_path(M.DEFAULT_GENERATED_ROOT, locale, slug)
      table.insert(files, {
        content = content,
        path = path,
      })
      table.insert(manifest_documents, {
        path = site_source_path(path),
        schema_version = M.PAGE_SCHEMA_VERSION,
        sha256 = sha256_hex(content, sha256_provider),
      })
    end
  end

  local routes_json = M.encode_json(build_routes(pages)) .. "\n"
  local routes_path = path_join(M.DEFAULT_DATA_ROOT, M.ROUTES_FILENAME)
  table.insert(files, {
    content = routes_json,
    path = routes_path,
  })
  table.insert(manifest_documents, {
    path = site_source_path(routes_path),
    schema_version = M.ROUTES_SCHEMA_VERSION,
    sha256 = sha256_hex(routes_json, sha256_provider),
  })

  table.sort(files, function(left, right)
    return left.path < right.path
  end)
  table.sort(manifest_documents, function(left, right)
    return left.path < right.path
  end)

  local manifest = {
    documents = manifest_documents,
    generator = "site-gen",
    schema_version = M.MANIFEST_SCHEMA_VERSION,
  }
  local manifest_json = M.encode_json(manifest) .. "\n"
  local manifest_path = path_join(M.DEFAULT_DATA_ROOT, M.MANIFEST_FILENAME)
  table.insert(files, {
    content = manifest_json,
    path = manifest_path,
  })

  return {
    files = files,
    manifest_documents = manifest_documents,
    manifest_json = manifest_json,
    routes_json = routes_json,
  }
end

function M.default_output_config()
  return {
    data_root = M.DEFAULT_DATA_ROOT,
    generated_root = M.DEFAULT_GENERATED_ROOT,
  }
end

local function relative_to_root(path, root)
  if path == root then
    return ""
  end
  local prefix = root .. "/"
  if path:sub(1, #prefix) ~= prefix then
    return nil
  end
  return path:sub(#prefix + 1)
end

local function validate_output_path(path)
  require_string(path, "output path")
  if path:find("%z") or path:find("\n", 1, true) or path:find("\r", 1, true) then
    error("output path contains an invalid path character")
  end
  local generated_rel = relative_to_root(path, M.DEFAULT_GENERATED_ROOT)
  local data_rel = relative_to_root(path, M.DEFAULT_DATA_ROOT)
  local rel = generated_rel or data_rel
  if rel == nil or rel == "" then
    error("output path is outside the generated site boundary: " .. path)
  end
  for segment in rel:gmatch("[^/]+") do
    validate_path_part(segment, "output path segment")
  end
  return path
end

local function parent_dir(path)
  return path:match("^(.*)/[^/]+$")
end

local function checked_files(config, artifact_set)
  if type(config) ~= "table" then
    error("output config must be an object")
  end
  validate_output_root(config.generated_root, M.DEFAULT_GENERATED_ROOT)
  validate_output_root(config.data_root, M.DEFAULT_DATA_ROOT)
  if type(artifact_set) ~= "table" or not is_array(artifact_set.files) then
    error("artifact set files must be an array")
  end

  local files = {}
  for _, output in ipairs(artifact_set.files) do
    local path = validate_output_path(output.path)
    if type(output.content) ~= "string" then
      error("output content must be a string")
    end
    table.insert(files, {
      content = output.content,
      path = path,
    })
  end
  table.sort(files, function(left, right)
    return left.path < right.path
  end)
  return files
end

function M.mkdir_outputs_cmd(config, artifact_set)
  local files = checked_files(config, artifact_set)
  local dirs = {}
  local seen = {}
  for _, output in ipairs(files) do
    local dir = parent_dir(output.path)
    if not seen[dir] then
      table.insert(dirs, dir)
      seen[dir] = true
    end
  end
  table.sort(dirs)
  local parts = { "mkdir -p" }
  for _, dir in ipairs(dirs) do
    table.insert(parts, M.shell_single_quote(dir))
  end
  return table.concat(parts, " ")
end

function M.output_temp_path(path)
  return validate_output_path(path) .. ".tmp"
end

function M.move_output_cmd(path)
  local final = validate_output_path(path)
  return "mv " .. M.shell_single_quote(final .. ".tmp") .. " " .. M.shell_single_quote(final)
end

function M.write_outputs_cmd(config, artifact_set)
  local files = checked_files(config, artifact_set)
  local commands = {}
  local mkdir_seen = {}
  for _, output in ipairs(files) do
    local path = output.path
    local dir = parent_dir(path)
    if not mkdir_seen[dir] then
      table.insert(commands, "mkdir -p " .. M.shell_single_quote(dir))
      mkdir_seen[dir] = true
    end
    local tmp = path .. ".tmp"
    table.insert(commands, "printf %s " .. M.shell_single_quote(output.content) .. " > " .. M.shell_single_quote(tmp))
    table.insert(commands, M.move_output_cmd(path))
  end

  return table.concat(commands, " && ")
end

return M
